# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

host: 0.0.0.0

# Site settings
title: Open Austin - Code for America Brigade - Austin, Texas
email: info@open-austin.org
description: Open Austin is a volunteer citizen brigade advocating for open government, open data, and civic application development since 2009. We are an official brigade affiliated with the nonprofit Code for America which believes government can work for the people, by the people in the 21st century. Open Austin is focused on the needs of our own community and we use design, technology, and open data to improve the quality of life in our city.
url: "http://open-austin.github.io/" # the base hostname & protocol for your site
twitter_username: openaustin
github_username:  open-austin
github_repo: https://github.com/open-austin/open-austin.github.io
collections:
  candidate-questionnaires:
    output: true
  projects:
    output: true

paginate: 10
paginate_path: "blog/page:num"

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: posts
    values:
      permalink: /blog/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude:
  - import

gems: [jekyll-paginate]
